[[protocols]]
name = "Philips Television"
protocol = "rc6"
variant = "rc-6-0"

[protocols.scancodes]
0x0c = "KEY_MACRO1" # Power
0x9f = "BTN_TRIGGER_HAPPY1" # TV
0x4b = "BTN_TRIGGER_HAPPY2" # Subtitle
0x3c = "BTN_TRIGGER_HAPPY3" # Teletext
0x38 = "BTN_TRIGGER_HAPPY4" # Source
0x6d = "BTN_TRIGGER_HAPPY5" # Red
0x6e = "BTN_TRIGGER_HAPPY6" # Green
0x6f = "BTN_TRIGGER_HAPPY7" # Yellow
0x70 = "BTN_TRIGGER_HAPPY8" # Blue
0xcc = "BTN_TRIGGER_HAPPY9" # Guide
0x54 = "BTN_TRIGGER_HAPPY10" # Home
0x40 = "BTN_TRIGGER_HAPPY11" # Options
0x58 = "BTN_TRIGGER_HAPPY12" # Up
0x59 = "BTN_TRIGGER_HAPPY13" # Down
0x5a = "BTN_TRIGGER_HAPPY14" # Left
0x5b = "BTN_TRIGGER_HAPPY15" # Right
0x5c = "BTN_TRIGGER_HAPPY16" # OK
0x0a = "BTN_TRIGGER_HAPPY17" # Back
0x0f = "BTN_TRIGGER_HAPPY18" # Info
0x2b = "BTN_TRIGGER_HAPPY19" # Rewind
0x2c = "BTN_TRIGGER_HAPPY20" # PausePlay
0x28 = "BTN_TRIGGER_HAPPY21" # Forward
0x31 = "BTN_TRIGGER_HAPPY22" # Stop
0x37 = "BTN_TRIGGER_HAPPY23" # Record
0x10 = "BTN_TRIGGER_HAPPY24" # Vol+
0x11 = "BTN_TRIGGER_HAPPY25" # Vol-
0x0d = "BTN_TRIGGER_HAPPY26" # Mute
0x20 = "BTN_TRIGGER_HAPPY27" # Ch+
0x21 = "BTN_TRIGGER_HAPPY28" # Ch-
0xf5 = "BTN_TRIGGER_HAPPY29" # Format
0x01 = "BTN_TRIGGER_HAPPY30" # 1
0x02 = "BTN_TRIGGER_HAPPY31" # 2
0x03 = "BTN_TRIGGER_HAPPY32" # 3
0x04 = "BTN_TRIGGER_HAPPY33" # 4
0x05 = "BTN_TRIGGER_HAPPY34" # 5
0x06 = "BTN_TRIGGER_HAPPY35" # 6
0x07 = "BTN_TRIGGER_HAPPY36" # 7
0x08 = "BTN_TRIGGER_HAPPY37" # 8
0x09 = "BTN_TRIGGER_HAPPY38" # 9
0x00 = "BTN_TRIGGER_HAPPY39" # 0
0xf4 = "BTN_TRIGGER_HAPPY40" # Sound
0xf3 = "KEY_MACRO2" # Picture
0x30 = "KEY_MACRO3" # Pause
0xba = "KEY_MACRO4" # 3D
0x8f = "KEY_MACRO5" # Light
0xbe = "KEY_MACRO6" # Smart TV
0xd2 = "KEY_MACRO7" # List
0x41 = "KEY_MACRO8" # Exit
0x4c = "KEY_MACRO9" # Ch+
0x4d = "KEY_MACRO10" # Ch-
